
use_frameworks!

abstract_target 'Pod' do

 pod 'CDBDownloader', :path => '../'

    target 'CDBDownloader_Example' do
        target 'CDBDownloader_Tests' do
            inherit! :search_paths
        end
    end
    target 'CDBDownloaderMac-Example' do
        #target 'CDBDownloaderMac-ExampleTests' do
        #    inherit! :search_paths
        #end
    end
end
